name: dbz_databook
description: "Dragon Ball Z - DataBook."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ##
  ## Core packages
  ##
  logger: ^2.0.2+1 ## Log tool
  dartz: ^0.10.1 ##Functional programming dart
  get_it: ^7.6.7 ##Dependency Injection
  bloc: ^8.1.3 ## base bloc package
  flutter_bloc: ^8.1.4 ## State Management Pattern
  dio: ^5.4.1 ## Http Client
  ##
  ## UI/Components Packages
  ##
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ## test mock

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
